### ISSUE TITLE
add more architectures to docker image

### ISSUE THREAD

**Issue by madiele** [amckee/PodTube#13]
Hi i'm currently working on this project https://github.com/madiele/vod2pod-rss
It's a service that takes any rss or youtube/twitch channel and rewrites it's enclosure to a live transcoded mp3 version of it so that you can play any youtube and twitch channels like if they were proper podcast in any client, my project already supports youtube but only the basic atom feed limited to 15 elements. I tried this project and it already works out of the box with mine and it's pretty awesome, I would like to add this service to the docker-compose as an optional dependency if that's cool with you, but since my images support armv7 and arm64 too I need them to be available, I can write you a PR with the required github actions if you want, or I can also do a fork and maintain my own version just to run the actions

**Comment by amckee** [comment]
I am new to Github actions, though I like the sound of your request. I'll be working through getting it going. If my progress is too slow, feel free to help in the [automated_builds](https://github.com/amckee/PodTube/tree/automated_builds) branch.

**Comment by madiele** [comment]
Nice! feel free to take inspiration from my deploy to docker hub action if you need some inspiration ✌️

**Comment by amckee** [comment]
Looks like I've finally got it working. Your docker action file certainly helped a lot! Both requested architectures are available now ( https://hub.docker.com/repository/docker/ftawesome/podtube/tags?page=1&ordering=last_updated )

**Comment by madiele** [comment]
Thanks a lot, I'll add it to my repo soon! I'll be sure to shout your repo out when I release v1.0 ✌️
